/*******************************************************************************
 * CLINOVO RESERVES ALL RIGHTS TO THIS SOFTWARE, INCLUDING SOURCE AND DERIVED BINARY CODE. BY DOWNLOADING THIS SOFTWARE YOU AGREE TO THE FOLLOWING LICENSE:
 * 
 * Subject to the terms and conditions of this Agreement including, Clinovo grants you a non-exclusive, non-transferable, non-sublicenseable limited license without license fees to reproduce and use internally the software complete and unmodified for the sole purpose of running Programs on one computer. 
 * This license does not allow for the commercial use of this software except by IRS approved non-profit organizations; educational entities not working in joint effort with for profit business.
 * To use the license for other purposes, including for profit clinical trials, an additional paid license is required. Please contact our licensing department at http://www.clinovo.com/contact for pricing information.
 * 
 * You may not modify, decompile, or reverse engineer the software.
 * Clinovo disclaims any express or implied warranty of fitness for use. 
 * No right, title or interest in or to any trademark, service mark, logo or trade name of Clinovo or its licensors is granted under this Agreement.
 * THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND. CLINOVO FURTHER DISCLAIMS ALL WARRANTIES, EXPRESS AND IMPLIED, INCLUDING WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.

 * LIMITATION OF LIABILITY. IN NO EVENT SHALL CLINOVO BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOSS OF PROFITS, REVENUE, DATA OR DATA USE, INCURRED BY YOU OR ANY THIRD PARTY, WHETHER IN AN ACTION IN CONTRACT OR TORT, EVEN IF ORACLE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. CLINOVO’S ENTIRE LIABILITY FOR DAMAGES HEREUNDER SHALL IN NO EVENT EXCEED TWO HUNDRED DOLLARS (U.S. $200).
 *******************************************************************************/
package org.akaza.openclinica.service.managestudy;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.akaza.openclinica.DefaultAppContextTest;
import org.akaza.openclinica.bean.login.UserAccountBean;
import org.akaza.openclinica.bean.managestudy.DiscrepancyNoteBean;
import org.akaza.openclinica.bean.submit.DisplayItemBean;
import org.akaza.openclinica.bean.submit.ItemBean;
import org.akaza.openclinica.bean.submit.ItemDataBean;
import org.akaza.openclinica.i18n.util.ResourceBundleProvider;
import org.junit.Before;
import org.junit.Test;
import org.powermock.core.classloader.annotations.PrepareForTest;

@PrepareForTest(ResourceBundleProvider.class)
public class DiscrepancyNoteServiceTest extends DefaultAppContextTest {

	private List<DisplayItemBean> changedItems;
	private Map<Integer, String> oldItemData;
	private List<String> changedItemNames;
	private UserAccountBean ub;
	private final String noteDescription = "CRF Evaluation Data Change";
	private final String detailedDescription = "Autogenerated during CRF Evalutation";
	private final String input = "input";

	@Before
	public void setUp() {
		changedItems = new ArrayList<DisplayItemBean>();
		changedItems.add(addDisplayItemToList(changedItems, 1500));
		changedItems.add(addDisplayItemToList(changedItems, 1501));
		changedItems.add(addDisplayItemToList(changedItems, 1502));
		changedItemNames = new ArrayList<String>();
		changedItemNames.add(input + 1500);
		changedItemNames.add(input + 1501);
		changedItemNames.add(input + 1502);
		oldItemData = new HashMap<Integer, String>();
		oldItemData.put(1, "0");
		oldItemData.put(2, "1");
		oldItemData.put(3, "2");
		ub = new UserAccountBean();
		ub.setId(1);
	}

	private DisplayItemBean addDisplayItemToList(List<DisplayItemBean> changedItems, int id) {
		DisplayItemBean displayItem = new DisplayItemBean();
		displayItem.setItem(new ItemBean());
		displayItem.getItem().setId(id);
		displayItem.setData(new ItemDataBean());
		displayItem.getData().setId(id);
		displayItem.getData().setValue("" + id);
		displayItem.getData().setItemId(id);
		displayItem.setDbData(new ItemDataBean());
		displayItem.getDbData().setId(id);
		displayItem.getDbData().setValue("" + (id - 1));
		displayItem.getDbData().setItemId(id);
		return displayItem;
	}

	@Test
	public void testThatRFCsAreGeneratedForChangedItems() {
		List<DiscrepancyNoteBean> annotations = discrepancyNoteService.generateRFCsForChangedFields(
				changedItems, changedItemNames, oldItemData, ub, noteDescription, detailedDescription);
		assertEquals(3, annotations.size());
	}

	@Test
	public void testThatRFCsAreNotGeneratedForEvalAddedData() {
		oldItemData.put(1502, "");
		List<DiscrepancyNoteBean> annotations = discrepancyNoteService.generateRFCsForChangedFields(
				changedItems, changedItemNames, oldItemData, ub, noteDescription, detailedDescription);
		assertEquals(2, annotations.size());
	}

	@Test
	public void testThatRFCsAreNotGeneratedForAddedDataAfterRepeatitiveSave() {
		DisplayItemBean displayItem = addDisplayItemToList(changedItems, 64);
		changedItems.add(displayItem);
		oldItemData.put(64, "");
		List<DiscrepancyNoteBean> annotations = discrepancyNoteService.generateRFCsForChangedFields(
				changedItems, changedItemNames, oldItemData, ub, noteDescription, detailedDescription);
		changedItems.remove(displayItem);
		oldItemData.remove(64);
		assertEquals(3, annotations.size());
	}
}