<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib uri="/WEB-INF/tlds/ui/ui.tld" prefix="ui" %>

<%@ page import="org.akaza.openclinica.logic.score.*, java.util.HashMap, java.util.ArrayList, org.akaza.openclinica.bean.submit.ResponseOptionBean, org.akaza.openclinica.bean.submit.ItemBean" %>

<c:set var="inputType" value="${param.inputType}" />
<c:set var="itemId" value="${param.itemId}" />
<c:set var="function" value="${param.function}"/>
<c:set var="linkText" value="${param.linkText}"/>
<c:set var="side" value="${param.side}"/>

<!-- *JSP* PAGE GENERATED BY generateLeftItemTxt.jsp <c:out value="${inputType}"/> <c:out value="${itemId}"/> -->
<c:out value="${linkText}" escapeXml="false"/>
