function leftnavExpand(strLeftNavRowElementName){
	var objLeftNavRowElement;
	var objExCl;
	objLeftNavRowElement = MM_findObj(strLeftNavRowElementName);
	if (objLeftNavRowElement != null) {
		if (objLeftNavRowElement.style) {
			objLeftNavRowElement = objLeftNavRowElement.style;
		}
		objLeftNavRowElement.display = (objLeftNavRowElement.display == "none" ) ? "" : "none";
	}
	objExCl = MM_findObj("excl_"+strLeftNavRowElementName);
	if (objExCl != null) {
		var newThemeColor = "${newThemeColor}";
		newThemeColor = newThemeColor == "green" || newThemeColor == "violet" || newThemeColor == "darkBlue" ? ("/" + newThemeColor) : "";
		if(objLeftNavRowElement.display == "none"){
			objExCl.src = "images" + newThemeColor + "/bt_Expand.gif";
		}else{
			objExCl.src = "images" + newThemeColor + "/bt_Collapse.gif";
		}
	}
}

function leftnavExpandExt(strLeftNavRowElementName){
	$("div[id="+strLeftNavRowElementName+"]").each(function() {
		leftnavExpand(strLeftNavRowElementName+'_3');
		leftnavExpand(strLeftNavRowElementName+'_4');
	});
}

function showMoreFields(index, name) {
	switch (name) {
		case 'RFC':
			var rowId = 'dnRFCDescriptionRow';
			break;
		case 'updateDescriptions':
			var rowId = 'dnUpdateDescriptionRow';
			break;
		case 'closeDescriptions':
			var rowId = 'dnCloseDescriptionRow';
			break;
	}
	for (var j=index+1; (j<26)&&(j<(index+3)); j++){
		$("tr#"+rowId+"_a"+j).show();
		$("tr#"+rowId+"_b"+j).show();
		$("tr#"+rowId+"_c"+j).show();
	}
}

$(document).ready(function() {
	var sections = new Array('3', '4', '5', '6', '6_1', '6_2', '6_3', '7');
	for (var j=0; j < sections.length; j++){
		if ($("div#section" + sections[j] + " span.alert").text() != '') {
			leftnavExpand("section" + sections[j]);
		}
	}

	$("input[data-cc-action][checked]").each(function(){
		hideUnhideStudyParamRow(this);
	});
});

function updateGeneratedSubjectId() {
	var prefix = $("#generatedIdPrefix").val();
	var separator = $("#generatedIdSeparator").val();
	var suffix = $("select[name=autoGeneratedSuffix]").val();
	var separatorItem = $("input[name=autoGeneratedSeparator]");
	var prefixItem = $("input[name=autoGeneratedPrefix]");
	if (prefix == "0") {
		prefixItem.hide();
		prefixItem.val("");
	} else if (prefix == "1") {
		prefixItem.hide();
		prefixItem.val("SiteID");
	} else {
		prefixItem.show();
		if (prefixItem.val() == "SiteID") {
			prefixItem.val("");
		}
	}
	if (separator == "0") {
		separatorItem.hide();
		separatorItem.val("");
	} else {
		separatorItem.show();
	}
	if (allFieldsForGeneratedIdAreValid()) {
		var idSuffix = Array(parseInt(suffix) + 1).join("X");
		var generatedId = prefixItem.val() + separatorItem.val() + idSuffix;
		var subjectIdHolder = $("#generated_id");
		subjectIdHolder.html(generatedId);
	}
}

function allFieldsForGeneratedIdAreValid() {
	var result = true;
	var separator = $("input[name=autoGeneratedSeparator]").val();
	var prefix = $("input[name=autoGeneratedPrefix]").val();
	var prefixRegexp = /[=!#\$%&\*\+\/\?`\^\{\|\}~'@:\\;\]\[]+/gm;
	var separatorRegexp = /[a-zA-Z0-9]+/gm;
	var submitButton = $("input[type=submit]");
	var prefixMessage = $("#autoGeneratedPrefixMessage");
	var separatorMessage = $("#autoGeneratedSeparatorMessage");

	if (prefixRegexp.test(prefix)) {
		prefixMessage.show();
		result = false;
	} else {
		prefixMessage.hide();
	}
	if (separatorRegexp.test(separator)) {
		separatorMessage.show();
		result = false
	} else {
		separatorMessage.hide();
	}
	if (!result) {
		submitButton.attr("disabled",true);
	} else {
		submitButton.removeAttr("disabled");
	}
	return result;
}

function updateInstanceType() {
	var selectInput = $(".instanceType");
	var textInput = $(".instanceTypeText");
	var activeName = "instanceType";
	var inactiveName = "instanceTypeNotUsed";

	if (selectInput.val() == "other") {
		selectInput.attr("name", inactiveName);
		textInput.attr("name", activeName).removeAttr("style");
	} else {
		selectInput.attr("name", activeName);
		textInput.attr("name", inactiveName).css("display", "none").val("");
	}
}
